services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE=http://backend:4000
