services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    expose:
      - "4000"
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE: ${REACT_APP_API_BASE:-http://backend:4000}
    depends_on:
      - backend
    expose:
      - "3000"
